version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: infection/infection
    versions:
    - 0.20.2
    - 0.21.0
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.0
    - 9.5.1
